### ISSUE TITLE
Color property fallback

### ISSUE THREAD

**Issue by dzhiriki** [maximkoretskiy/postcss-initial#15]
Why fallback for `color: initial` is a `color: inherit`? 
It's gave different result. [Example](https://jsfiddle.net/nu51srx0/)
`Initial` is a browser default color. Does it has to be `black`?

**Comment by Nitive** [comment]
`font-family` and `text-align` inherit too.
Should it be `sans-serif` and `left`?

**Comment by sylvainbaronnet** [comment]
`color`, `font-family` and `text-align` are inherited by default so I think `inherit` is the right fallback

**Comment by maximkoretskiy** [comment]
You are right. I will check all inherit props and create fix after some experiments.

**Comment by maximkoretskiy** [comment]
Hi, guys. Sorry for long response. After some experiments, I'm sure that we can replace all `inherit` values with something more specific. 

Here is current changeset. https://gist.github.com/maximkoretskiy/8b2ede7f06cfdb7a78c0

The only thing we can't fix without any doubt is `text-align`. It depends on browser default text direction. There is a modern way to set universal initial value for text-align: `text-align: start`. But it doesn't work in old browsers.

Have U any idea for this case?

**Comment by maximkoretskiy** [comment]
@ai We need your advice

**Comment by ai** [comment]
I think `color: inherit` is a bad thing. All inherited styles should be declared explicit:

``` css
all: inital;
font: inherit;
```

**Comment by Nitive** [comment]
`direction` is already reseted to `ltr` so I think `text-align: left` is right fallback.

**Comment by maximkoretskiy** [comment]
Just published new release.
