### ISSUE TITLE
Two valued syntax doesn't seem to be supported.

### ISSUE THREAD

**Issue by johnbender** [maximkoretskiy/postcss-initial#16]
I've looked around in the code a bit here and in the postcss-cssnext docs and it appears as though two (or more) valued syntax with `initial` values is not supported, e.g. `background-repeat: initial initial` ([mdn docs](https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat#Syntax))

At a minimum it doesn't seem to be working in the cssnext playground:

![screenshot 2016-04-06 22 14 47](https://cloud.githubusercontent.com/assets/23505/14341365/1ba73d44-fc46-11e5-89d5-0a74b30960b1.png)

I don't mind looking at the code a bit more closely and submitting a PR but I figured I should make sure I'm not missing something obvious first.

Thanks!

**Comment by maximkoretskiy** [comment]
Hi, and thank You for this issue.
You are right.

**Comment by johnbender** [comment]
@maximkoretskiy 

Thanks for the speedy reply! I'll see if I can get some time to hack around and submit a PR.

**Comment by maximkoretskiy** [comment]
:+1:

**Comment by maximkoretskiy** [comment]
Just released. Thank You

**Comment by johnbender** [comment]
👍
