### ISSUE TITLE
Include fallback for outline using currentColor for browsers that don't support invert

### ISSUE THREAD

**Issue by colinkahn** [maximkoretskiy/postcss-initial#21]
![screen shot 2017-01-12 at 1 09 08 pm](https://cloud.githubusercontent.com/assets/1444385/21908423/89996638-d8c8-11e6-8a27-74126f3d7c14.png)
![screen shot 2017-01-12 at 1 07 49 pm](https://cloud.githubusercontent.com/assets/1444385/21908422/8995d7b6-d8c8-11e6-8df9-1a6a5cc7c45f.png)

via: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color

Proposing to add `outline: medium none currentColor;` as a fallback.

**Comment by romainmenke** [comment]
No browser supports `invert` and `invert` itself is at risk of being removed from the specification.
