### ISSUE TITLE
3.0 sources are missing on github

### ISSUE THREAD

**Issue by just-boris** [maximkoretskiy/postcss-initial#28]
Npm shows that the latest version is 3.0: https://www.npmjs.com/package/postcss-initial

But there is still 2.0 on Github: https://github.com/maximkoretskiy/postcss-initial/blob/master/package.json#L3

Where are the sources for the latest release?

**Comment by maximkoretskiy** [comment]
Hi and thank u. Just pushed it

**Comment by just-boris** [comment]
Wonderful. Thank you!
