### ISSUE TITLE
Vulnerability Issue

### ISSUE THREAD

**Issue by ZeRego** [maximkoretskiy/postcss-initial#29]
We need to upgrade `lodash.template` dependency to 4.5.0 or later.
 
**Github vulnerability report:** 
https://github.com/trayio/embedded-edition-sample-app/network/alert/package-lock.json/lodash.template/open

**Lodash pull request with fix:**
https://github.com/lodash/lodash/pull/4336

**Comment by maximkoretskiy** [comment]
thanks! will fix it soon

**Comment by maximkoretskiy** [comment]
Just published new version

**Comment by ZeRego** [comment]
thanks for the quick response
