### ISSUE TITLE
Small reset subset

### ISSUE THREAD

**Issue by ai** [maximkoretskiy/postcss-initial#3]
Maybe we should add options `reset: 'small'`, which will insert most important but not all rules.

Like rules, that can be inherit from parents. For example, `animation` can’t be inherit, so we can remove it.

**Comment by maximkoretskiy** [comment]
@ai Good idea. 
We can create some properties subsets:
- small;
- sizes;
- full;
- uninherited;

**Comment by ai** [comment]
Yeap, maybe `inherited` is a better name than `small`

**Comment by maximkoretskiy** [comment]
@ai  What subset should plugin use by default? all or inherited?

**Comment by ai** [comment]
Seems like `all`, because it is how spec works :(

**Comment by maximkoretskiy** [comment]
@ai implemented in `feature/subsets`
I have idea to add some other subsets such as
- sizes (width, height, sizings, borders, margins)
- texts styling
  What do you think bout it?

**Comment by ai** [comment]
Yeap, but we need different CSS API for text. Maybe it should be in `postcss-autoreset`?

**Comment by maximkoretskiy** [comment]
Looks fine. `postcss-autoreset` will reset rules by different sets of rules.
- `all: unset`   or
- sizes or 
- texts or
- some universal set

@ai can we finish with this feature?

**Comment by maximkoretskiy** [comment]
@ai

**Comment by ai** [comment]
Nope, we need `inherited` options for `unset`, because it is looks like non-100% but better polyfills.

**Comment by maximkoretskiy** [comment]
We have `reset` option.

https://github.com/maximkoretskiy/postcss-all-unset#reset

Should  I rename it to `unset`?

**Comment by ai** [comment]
Nope, your name is much better, I just miss a commit.
