### ISSUE TITLE
High Severity security issue with lodash.template

### ISSUE THREAD

**Issue by charlieTheBotDev** [maximkoretskiy/postcss-initial#44]
https://snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054

`lodash.template` is deprecated - Please swap to use `lodash` and import `template` from that

This is causing issues in many of our production applications so would appreciate a swift resolution

```
postcss-preset-env@6.7.0
  └─┬ postcss-initial@3.0.2
    └── lodash.template@4.5.0 
```

Cross-posted for visibility: https://github.com/csstools/postcss-preset-env/issues/203

**Comment by candrews** [comment]
Please release version `3.0.3` when this change is made so (the many) packages that depend upon `postcss-initial` `3.x` can benefit.

Thank you!

**Comment by JavaZava** [comment]
There is already a version `4.0.0` released, but it still has the `lodash.template` dependency.

**Comment by maximkoretskiy** [comment]
@candrews sure. will do
