### ISSUE TITLE
Publish v4 to npm?

### ISSUE THREAD

**Issue by doochik** [maximkoretskiy/postcss-initial#47]
v4 with postcss8 support is still unpublished at npm.

Latest published version - 3.0.4
https://www.npmjs.com/package/postcss-initial

Could you publish it?

**Comment by maximkoretskiy** [comment]
4.0.1 is published also. 3.0.4  is the last published because of major bugs fixes for PostCSS v7 audience

<img width="633" alt="изображение" src="https://user-images.githubusercontent.com/2323027/142037127-37cb9a6c-c22d-42f0-9b3d-8bea9ceb2e29.png">

**Comment by doochik** [comment]
Thanks!
