### ISSUE TITLE
OneDrive Sync Issue with the folder name < ~ > Tilde

### ISSUE THREAD

**Issue by joephoton** [maximkoretskiy/postcss-initial#48]
The folder with the folder name < ~ > as seen in the attached image Issue2 doesn't allow OneDrive to Sync as the tilde is an illegal character as seen in the attached image Issue1.

Was wondering if we could maybe change it to another naming convention.

![issue1](https://user-images.githubusercontent.com/29985737/168335063-102a5306-0062-4ac5-aca0-d10d248be04f.PNG)
![issue2](https://user-images.githubusercontent.com/29985737/168335064-128852f1-1335-48ff-ab73-eb78c6dccd9d.PNG)

**Comment by maximkoretskiy** [comment]
The directory `~` could not be created by any of the functionalities of `postcss-initial`.
I suspect it is somehow connected to your local setup. Some shell applications can put their local configurations in such a manner.

**Comment by azuroff** [comment]
@joephoton Did you ever figure out what was creating that directory?  I'm running into the same issue, but only in this module.
