### ISSUE TITLE
Add to cssnext

### ISSUE THREAD

**Issue by ai** [maximkoretskiy/postcss-initial#5]
Good open source is not only good code, it is good promotion.

To be popular, you need to add your plugin to [cssnext](http://cssnext.io/) plugin pack.

**Comment by maximkoretskiy** [comment]
Waiting for https://github.com/cssnext/cssnext/issues/202

**Comment by sylvainbaronnet** [comment]
FYI cssnext/cssnext#202 is closed

**Comment by maximkoretskiy** [comment]
@sylvainbaronnet Yes, U are right. But Im waiting for support postcss 5 in cssnext. And this feature moved to another issue
